import Head from 'next/head'
import Navbar from '../components/layout/navbar/Navbar'

export default function Archive() {
  return (
    <div>
      <Head>
        <title>AWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
