import Head from 'next/head'
import { useState } from 'react'
import ArchiveModal from '../components/layout/archive/ArchiveModal'
import ReportFormModal from '../components/layout/generator/ReportFormModal'

export default function Archive({locale, data, dataAll }) {

  const [singleReportData, setSingleReportData] = useState(null)
  const [mode, setMode] = useState('Werkstatt')

  function handleMode() {
    if (mode == 'Werkstatt') {
      setMode('Tunap')
    } else {
      setMode('Werkstatt')
    }
  }

  return (
    <div>
      <Head>
        <title>AWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {singleReportData == null ? (
        <>
          <div className='flex justify-center my-2'>
            <div className='inline p-2 border-4' onClick={() => handleMode()}>{mode} {mode == 'Werkstatt' ? (
              <span>(Gelöschte nicht Anzeigen)</span>
            ) : (
              <span>(Gelöschte Anzeigen)</span>
            ) }</div>
          </div>
          <div className={`${mode == 'Werkstatt' ? "" : "hidden"}`}>
            <ArchiveModal locale={locale} data={data} setSingleReportData={setSingleReportData} />
          </div>
          <div className={`${mode == 'Tunap' ? "" : "hidden"}`}>
            <ArchiveModal locale={locale} data={dataAll} setSingleReportData={setSingleReportData} />
          </div>
        </>
      ) : (
        <ReportFormModal locale={locale} singleReportData={singleReportData} setSingleReportData={setSingleReportData} />
      )}
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from reports API
  const res = await fetch(process.env.FETCH_URL + '/api/reporthandler/reports', {
    method: 'post',
    body: 'false'
  })
  const data = await res.json()

  const resAll = await fetch(process.env.FETCH_URL + '/api/reporthandler/reports', {
    method: 'post',
    body: 'true'
  })
  const dataAll = await resAll.json()

  // Pass data to the page via props
  return {
    props: {
      data,
      dataAll
    }
  }
}