import Head from 'next/head'
import Navbar from '../components/layout/navbar/Navbar'
import Title from '../components/elements/Title'


export default function Home() {
  return (
    <div>
      <Head>
        <title>AWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

