import Head from 'next/head'
import ReportGeneratorModal from '../components/layout/generator/ReportGeneratorModal'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReportGeneratorModal></ReportGeneratorModal>
    </div>
  )
}

