import Head from 'next/head'
import ReportFormModal from '../components/layout/generator/ReportFormModal'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReportFormModal/>
    </div>
  )
}

